AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  DepLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: forgeapi-dependencies
      ContentUri: s3://pkhafizov-forge-s3/layers/9e1389c1590f222c704107d7827298da
      CompatibleRuntimes:
      - nodejs12.x
      LicenseInfo: MIT
      RetentionPolicy: Retain
